{
 "title": "Piante",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Umidità",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_plant_id",
     "query": "SELECT \"plant_id\", \"humidity\" as value FROM \"autogen\".\"kafka_consumer\" WHERE $timeFilter GROUP BY \"plant_id\"::tag fill(null)"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_plant_id",
     "query": "SELECT \"plant_id\", \"temperature\" as value FROM \"autogen\".\"kafka_consumer\" WHERE $timeFilter GROUP BY \"plant_id\"::tag fill(null)"
    }
   ]
  },
  {
   "title": "Luminosità",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_plant_id",
     "query": "SELECT \"plant_id\", \"luminosity\" as value FROM \"autogen\".\"kafka_consumer\" WHERE $timeFilter GROUP BY \"plant_id\"::tag fill(null)"
    }
   ]
  }
 ]
}